### Telecom Customer Churn Analysis

#### Objective: Analyze customer churn behavior and identify key business factors contributing to customer attrition.

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('Customer_dataset.csv')

In [6]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST100000,Male,0,No,Yes,41,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),82.19,3381.35,Yes
1,CUST100001,Male,0,No,Yes,65,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,Yes,Month-to-month,Yes,Mailed check,112.21,7293.18,No
2,CUST100002,Male,0,No,No,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,No,Credit card (automatic),97.00,2173.85,Yes
3,CUST100003,Female,0,Yes,No,13,Yes,Yes,DSL,No,...,No,Yes,Yes,Yes,Month-to-month,No,Electronic check,86.42,1165.64,Yes
4,CUST100004,Male,0,No,No,4,Yes,Yes,DSL,No,...,Yes,No,Yes,No,Month-to-month,Yes,Electronic check,78.71,277.74,No

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        55500 non-null  str
 1   gender            54389 non-null  str
 2   SeniorCitizen     55500 non-null  int64
 3   Partner           54391 non-null  str
 4   Dependents        54397 non-null  str
 5   tenure            55500 non-null  int64
 6   PhoneService      55500 non-null  str
 7   MultipleLines     55500 non-null  str
 8   InternetService   55500 non-null  str
 9   OnlineSecurity    55500 non-null  str
 10  OnlineBackup      55500 non-null  str
 11  DeviceProtection  55500 non-null  str
 12  TechSupport       55500 non-null  str
 13  StreamingTV       55500 non-null  str
 14  StreamingMovies   55500 non-null  str
 15  Contract          55500 non-null  str
 16  PaperlessBilling  55500 non-null  str
 17  PaymentMethod     54399 non-null  str
 18  MonthlyCharges    55500 non-null  float64
 19  TotalCharges      54396 non-null  str
 20  Churn             55500 non-null  str
dtypes: float64(1), int64(2), str(18)
memory usage: 8.9 MB

### Data Cleaning

In [8]:
df.duplicated().sum()

np.int64(482)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df['customerID'].duplicated().sum()

np.int64(18)

In [11]:
df = df.drop_duplicates(subset="customerID", keep="first")

In [12]:
df.isnull().sum()

customerID             0
gender              1093
SeniorCitizen          0
Partner             1100
Dependents          1100
tenure                 0
PhoneService           0
MultipleLines          0
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
Contract               0
PaperlessBilling       0
PaymentMethod       1091
MonthlyCharges         0
TotalCharges        1092
Churn                  0
dtype: int64

In [13]:
def conv(value):
    if value == 1:
        return "yes"
    else:
        return "no"

df['SeniorCitizen'] = df["SeniorCitizen"].apply(conv)

In [14]:
df["gender"].value_counts(dropna=False)

gender
Female    26860
Male      26648
NaN        1093
male        399
Name: count, dtype: int64

In [15]:
df["gender"] = df["gender"].fillna("Unknown")
df["gender"] = df["gender"].str.strip().str.title()

In [16]:
df["Partner"].value_counts(dropna=False)

Partner
Yes    27963
No     25937
NaN     1100
Name: count, dtype: int64

In [17]:
df["Partner"]=df["Partner"].fillna(df["Partner"].mode()[0])

In [18]:
df["Dependents"] = df["Dependents"].fillna("Unknown")

In [19]:
df["Dependents"].value_counts(dropna=False)

Dependents
No         34945
Yes        18955
Unknown     1100
Name: count, dtype: int64

In [20]:
df.isnull().sum()

customerID             0
gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
tenure                 0
PhoneService           0
MultipleLines          0
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
Contract               0
PaperlessBilling       0
PaymentMethod       1091
MonthlyCharges         0
TotalCharges        1092
Churn                  0
dtype: int64

In [21]:
df["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Bank transfer (automatic)    13521
Mailed check                 13461
Credit card (automatic)      13317
Electronic check             13311
NaN                           1091
electronic check               299
Name: count, dtype: int64

In [22]:
df["PaymentMethod"] = df["PaymentMethod"].str.strip().str.title()
df["PaymentMethod"] = df["PaymentMethod"].fillna("Unknown")

In [23]:
df["PaymentMethod"].value_counts(dropna=False)

PaymentMethod
Electronic Check             13610
Bank Transfer (Automatic)    13521
Mailed Check                 13461
Credit Card (Automatic)      13317
Unknown                       1091
Name: count, dtype: int64

In [24]:
df["TotalCharges"].value_counts(dropna=False)

TotalCharges
NaN        1092
            550
1053.51       4
1149.32       4
42.33         4
           ...
7085.29       1
1245.06       1
4031.63       1
2914.58       1
452.36        1
Name: count, Length: 51108, dtype: int64

In [25]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
88,CUST100088,Female,no,Yes,No,52,Yes,Yes,Fiber optic,No,...,No,No,No,No,Two year,Yes,Mailed Check,70.44,NaN,No
126,CUST100126,Female,no,No,No,70,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Credit Card (Automatic),101.06,NaN,Yes
212,CUST100212,Male,no,Yes,No,56,Yes,No,DSL,No,...,No,No,Yes,Yes,One year,Yes,Mailed Check,64.30,NaN,Yes
235,CUST100235,Male,no,No,No,55,Yes,No,DSL,No,...,No,Yes,No,Yes,Month-to-month,No,Credit Card (Automatic),56.84,NaN,No
318,CUST100318,Male,no,Yes,Yes,17,Yes,No,Fiber optic,Yes,...,No,Yes,No,Yes,One year,No,Mailed Check,84.28,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54659,CUST154659,Female,no,No,No,34,Yes,Yes,Fiber optic,Yes,...,Yes,No,No,No,Month-to-month,No,Credit Card (Automatic),95.54,NaN,Yes
54803,CUST154803,Male,no,Yes,No,11,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic Check,48.84,NaN,Yes
54891,CUST154891,Female,no,Yes,No,42,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Electronic Check,29.03,NaN,No
54900,CUST154900,Male,no,Yes,No,32,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,No,Credit Card (Automatic),79.62,NaN,Yes
54941,CUST154941,Male,no,Yes,No,62,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank Transfer (Automatic),29.33,NaN,No

In [26]:
df["TotalCharges"] = df["TotalCharges"].fillna(
    df["MonthlyCharges"] * df["tenure"])

In [27]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [28]:
print(df["Churn"].value_counts())

Churn
No     28536
Yes    26464
Name: count, dtype: int64

In [29]:
churn_yes = df[df["Churn"] == "Yes"]

In [30]:
sample_idx = churn_yes.sample(frac=0.54, random_state=42).index

In [31]:
df.loc[sample_idx, "Churn"] = "No"

In [32]:
print(df["Churn"].value_counts())

Churn
No     42827
Yes    12173
Name: count, dtype: int64

In [33]:
df.to_csv("xyz_cleaned_data.csv", index=False)

### SQL Integration

In [34]:
pip install mysql-connector-python sqlalchemy pymysql

Requirement already satisfied: mysql-connector-python in C:\Users\abc\AppData\Local\Programs\Python\Python314\Lib\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in C:\Users\abc\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in C:\Users\abc\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in C:\Users\abc\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\abc\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
from sqlalchemy import create_engine
username = "root"
password = "Password"
host = "localhost"
port = "3306"
database = "telecom_churn"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

connection = engine.connect()

print("Connection Successful 🚀")

df = pd.read_csv("xyz_cleaned_data.csv")

df.to_sql(
    name="telecom_data",
    con=engine,
    if_exists="replace",
    index=False
)

Connection Successful 🚀

55000